version: "3.9"
services:
  server:
    ports: 
        - 8888:80
        - 5000:5000
    volumes: 
        - C:/Users/hbroc/Documents/Projects/personal-site/server/PersonalServer:/app
        - C:/Users/hbroc/Documents/Projects/personal-site/server/PersonalServer:/src/
        - C:/Usershbroc/AppData/Roaming/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - C:/Users/hbroc/AppData/Roaming/ASP.NET/Https:/root/.aspnet/https:ro 
        - C:/Users/hbroc/.nuget/packages/:/root/.nuget/fallbackpackages
    build:
      context: ../server/PersonalServer
      dockerfile: ../../docker/test.Dockerfile
    image: server-image